const hints = {
  'א': {
    country: 'אוסטרליה',
    city: 'אמסטרדם',
    animal: 'ארנב',
    plant: 'אגס',
    name: 'אורי',
    profession: 'אופה',
    food: 'אבטיח',
    movie: 'אווטאר',
  },
  'ב': {
    country: 'ברזיל',
    city: 'ברלין',
    animal: 'ברבור',
    plant: 'בננה',
    name: 'בן',
    profession: 'בנאי',
    food: 'בורגר',
    movie: 'בטמן',
  },
  'ג': {
    country: 'גרמניה',
    city: 'גנבה',
    animal: 'גמל',
    plant: 'גזר',
    name: 'גיל',
    profession: 'גנן',
    food: 'גלידה',
    movie: 'גוסטו',
  },
  'ד': {
    country: 'דנמרק',
    city: 'דובאי',
    animal: 'דב',
    plant: 'דקל',
    name: 'דן',
    profession: 'דייג',
    food: 'דבש',
    movie: 'דיסני',
  },
  'ה': {
    country: 'הונגריה',
    city: 'הלסינקי',
    animal: 'הדרקון',
    plant: 'הדס',
    name: 'הלה',
    profession: 'הנדסאי',
    food: 'המבורגר',
    movie: 'הארי פוטר',
  },
  'ז': {
    country: 'זימבבואה',
    city: 'זגרב',
    animal: 'זאב',
    plant: 'זית',
    name: 'זיו',
    profession: 'זמר',
    food: 'זוקיני',
    movie: 'זוטופיה',
  },
  'ח': {
    country: 'צ\'ילה',
    city: 'חיפה',
    animal: 'חתול',
    plant: 'חמנייה',
    name: 'חן',
    profession: 'חייל',
    food: 'חומוס',
    movie: 'חפרפרת',
  },
  'י': {
    country: 'יפן',
    city: 'ירושלים',
    animal: 'יונה',
    plant: 'יסמין',
    name: 'יובל',
    profession: 'יועץ',
    food: 'יוגורט',
    movie: 'יש לי חבר',
  },
  'כ': {
    country: 'כווית',
    city: 'קייב',
    animal: 'כלב',
    plant: 'כרוב',
    name: 'כרמל',
    profession: 'כימאי',
    food: 'כרוב',
    movie: 'כוחות מיוחדים',
  },
  'ל': {
    country: 'לבנון',
    city: 'לונדון',
    animal: 'לביאה',
    plant: 'לימון',
    name: 'לירן',
    profession: 'לוחם',
    food: 'לחם',
    movie: 'לוח הזמנים',
  },
  'מ': {
    country: 'מקסיקו',
    city: 'מדריד',
    animal: 'מלך ים',
    plant: 'מנגו',
    name: 'מיכל',
    profession: 'מורה',
    food: 'מרק',
    movie: 'מלך האריות',
  },
  'נ': {
    country: 'נורווגיה',
    city: 'ניו יורק',
    animal: 'נמר',
    plant: 'נרקיס',
    name: 'נועה',
    profession: 'נגר',
    food: 'נחינה',
    movie: 'נמו',
  },
  'ס': {
    country: 'ספרד',
    city: 'סידני',
    animal: 'סוס',
    plant: 'סברס',
    name: 'שרה',
    profession: 'סופר',
    food: 'סושי',
    movie: 'סינדרלה',
  },
  'ע': {
    country: 'עיראק',
    city: 'עכו',
    animal: 'עיט',
    plant: 'ענב',
    name: 'עמית',
    profession: 'עורך דין',
    food: 'ענבים',
    movie: 'עוזי',
  },
  'פ': {
    country: 'פורטוגל',
    city: 'פריז',
    animal: 'פרה',
    plant: 'פרח',
    name: 'פז',
    profession: 'פיזיותרפיסט',
    food: 'פסטה',
    movie: 'פינוקיו',
  },
  'ר': {
    country: 'רוסיה',
    city: 'רומא',
    animal: 'ריחן',
    plant: 'רימון',
    name: 'רון',
    profession: 'רופא',
    food: 'רוטב',
    movie: 'רטטוי',
  },
  'ש': {
    country: 'שבדיה',
    city: 'שנחאי',
    animal: 'שועל',
    plant: 'שושן',
    name: 'שי',
    profession: 'שוטר',
    food: 'שוקולד',
    movie: 'שרק',
  },
  'ת': {
    country: 'תאילנד',
    city: 'תל אביב',
    animal: 'תנין',
    plant: 'תאנה',
    name: 'תמר',
    profession: 'תזונאי',
    food: 'תפוח',
    movie: 'תולעת',
  },
};

function getHint(letter, categoryId) {
  return hints[letter]?.[categoryId] ?? null;
}

module.exports = { getHint };
